### ISSUE TITLE
[SUGGESTION] Add Tag button in "Search Tag" window when Tag cannot be found by the app

### ISSUE THREAD

**Issue by Maxello1** [TagStudioDev/TagStudio#1]
example image

![Untitled-1](https://github.com/CyanVoxel/TagStudio/assets/98433747/ace5d96f-c0bb-4449-ab23-935e46a2e524)

**Comment by Wuffli** [comment]
What about, instead of a "new"  button (or maybe in addition?), whenever you type something in the search box that does not exist yet, there is a suggestion in the scroll view, asking if you want to add your search entry as a new Tag. And also you could add a new Tag just by hitting enter.

**Comment by Maxello1** [comment]
good idea, would need to have a "workaround" for the color tag tho (the "on enter press" option i guess)

**Comment by LennartCode** [comment]
> And also you could add a new Tag just by hitting enter.

(Under the premise I didn't misunderstand anything)
I would advice against automatically adding a tag if a non-existent tag name is typed and enter is pressed afterwards.
If the user made a typo and just wanted to add an existing tag, this would add the wrong tag, often without the user noticing. This can lead to mislabelled data and even if the user realised the mistake, they would need to remove the tag from the file and depending on the implementation delete the tag with the typo altogether, leading to terrible UX in the best and terrible meta-data in the worst case.

**Comment by LunaLorea** [comment]
I think this can be easily addressed by good highlighting and a 'do you really want to add this new tag'.
But also this is a feature that is common and seems to work (at least for me). For an example see the 'open or create file' dialogue in obsidian (ctrl + o).

In any case, I see your concern but I think having a keyboard shortcut to add a new tag is important since it makes using  the app so much more comfortable.

**Comment by CyanVoxel** [comment]
Having an extra dialog confirmation, as well as being able to edit extra information about the tag besides just the name, I think is a good way to go about it. As well as keeping the ability to do it all via the keyboard so you don't lose that flow.

**Comment by PeterBouSaada** [comment]
You can have pressing Enter open up the tag creation menu, with the tag name populated, that way the user gets to configure other things and they have to confirm creation as well.

**Comment by Computerdores** [comment]
With #262 having been merged, I think this can be closed.
