### ISSUE TITLE
Visual bug with the edit pencil when sorting fields

### ISSUE THREAD

**Issue by Loran425** [TagStudioDev/TagStudio#115]
## Expected Behavior
Pencil Edit icon disappears when a change in the sort order results in the cursor hovering over a field that normally doesn't show an edit icon

## Current Behavior
When using the `alt+s` shortcut to sort fields if the pencil icon is shown on a field and a field that doesn't normally show that icon (e.g. a tag group) ends up under the cursor the edit pencil will remain on that widget until the fields widget is redrawn.

## Possible Solution
Check how these icons are drawn/removed and remove the icons prior to sorting

## Steps to Reproduce
![image](https://github.com/TagStudioDev/TagStudio/assets/7898215/2f498510-49f8-4a74-9959-624760de2c93)
1. Add a tag group
2. Add an author tag
3. Hover over the author tag
4. Press `alt+s` to sort the fields

**Comment by CyanVoxel** [comment]
Just wanted to follow-up and see if #189 resolved this issue, as I wasn't able to reproduce it before or after that PR.

**Comment by Loran425** [comment]
Confirmed Resolved
