### ISSUE TITLE
filename text search

### ISSUE THREAD

**Issue by pogotar** [TagStudioDev/TagStudio#144]
tag studio would do wonders for my phd where I have to go trough a hell lot of folders filled by loads of people.
I work with matlab codes which are not easily identifiable form a visual UI unlike photos for example.
To put a tag I really need to search the file with its name.
Right now I couldn't find a way to do that which seems strange since it is a very basic thing.

Please tell me if it is a missing feature or if I haven't understand how to do it.

Thank you!

**Comment by CyanVoxel** [comment]
You can currently search via filenames by typing `filename: <name of your file>` into the search bar :)

**Comment by yedpodtrzitko** [comment]
This sounds like an UX/UI issue where this functionality is not easily discoverable. 

Perhaps there can be added a placeholder in the search field or help text next to the field with the possible search options.

**Comment by CyanVoxel** [comment]
> This sounds like an UX/UI issue where this functionality is not easily discoverable.
> 
> Perhaps there can be added a placeholder in the search field or help text next to the field with the possible search options.

Absolutely. The search functionality as a whole is very barebones, with stuff like the filename search being bolted on with the only reference being in the readme. Doing a proper search overhaul with improved UI/UX is likely to be the next big project after the DB migration is complete. In the meantime, this is a good start for considering how best to display to the user what additional capabilities are available.

As an example for how this could look in the program, Obsidian has this popup under the search bar when typing which shows you different filtering options. I'm not a fan of how it covers up the controls underneath this every time you type, though...
![image](https://github.com/TagStudioDev/TagStudio/assets/46939827/802330ae-5829-4ccc-93f0-ad59b413d1b2)

**Comment by pogotar** [comment]
Thank you so much it worked!!

**Comment by pogotar** [comment]
thank you so much it worked!!
