### ISSUE TITLE
any plan for docker support?

### ISSUE THREAD

**Issue by coracoo** [TagStudioDev/TagStudio#146]
any plan for docker support?

**Comment by yedpodtrzitko** [comment]
how would the application running inside container work with files on the host machine? 🤔

**Comment by coracoo** [comment]
did`-v /host/folder:/container/folder` works?

**Comment by yedpodtrzitko** [comment]
and the more important question - Is there a way how to a GUI application in Docker?

**Comment by yedpodtrzitko** [comment]
I think we can close this since the binaries render this obsolete.

**Comment by coracoo** [comment]
ok, I will close it
