### ISSUE TITLE
[Feature Request] Add the ability to delete tags

### ISSUE THREAD

**Issue by chaotic-dev** [TagStudioDev/TagStudio#148]
The ability to delete a tag that is no longer used and have it removed from all files would be be convenient. Tags can be renamed and repurposed, but it does not appear that they are able to be deleted once created.

**Comment by Loran425** [comment]
#105 adds this as an option to the Tag Database menu option.

**Comment by dxnxz** [comment]
+1 :)

**Comment by CyanVoxel** [comment]
**(FINALLY)** added in #569 🎉
