### ISSUE TITLE
Run the progam via mouse click

### ISSUE THREAD

**Issue by GereonW** [TagStudioDev/TagStudio#152]
It would be nice to have a batch file that starts TagStudio just by clicking on it.
Since you need to activate venv at the moment you can't just run the program via python.

I wrote a batch for windows:

TagStudio.bat
```
@echo off
call .venv\Scripts\activate.bat
start .venv\Scripts\python.exe .\TagStudio\tag_studio.py --ui qt %*
```

Please add it as a file so no one needs to add it everytime you update.
Feel free to add a script for Linux in the comments.

**Comment by CyanVoxel** [comment]
This actually [already exists](https://github.com/TagStudioDev/TagStudio/blob/main/start_win.bat), with instructions on how to use it in the [Windows](https://github.com/TagStudioDev/TagStudio?tab=readme-ov-file#windows) section of the README instructions. Likewise a [Linux/macOS](https://github.com/TagStudioDev/TagStudio/blob/main/TagStudio.sh) version was already created as well.
