### ISSUE TITLE
[BUG] Small pixel art is blurry and doesn't fit in image preview

### ISSUE THREAD

**Issue by DeLoR1AnEc** [TagStudioDev/TagStudio#174]
![image](https://github.com/TagStudioDev/TagStudio/assets/100530521/e4761511-4f3c-4fd8-a1af-042c95d01ae7)

**Comment by CyanVoxel** [comment]
I can get this addressed soon. The blurriness will be a simple fix but I'm not sure what you mean by how an image "doesn't fit in image preview". All of the pixels from the original images are displayed in thumbnails you've shown, just with the bilinear filtering making them look a bit wonky. When I fix the blurriness by changing to a "nearest neighbor" filtering mode, they appear as this:

![image](https://github.com/TagStudioDev/TagStudio/assets/46939827/b9580dc6-4a5a-4940-8f58-55b5600da8f9)

I just want to make sure that you're not referring to a different issue that I can't see or am not aware of.

**Comment by DeLoR1AnEc** [comment]
It seems like it looked "cropped" because of blur, so now everything is okay.
