### ISSUE TITLE
[BUG] Blank background is sometimes black and sometimes white

### ISSUE THREAD

**Issue by DeLoR1AnEc** [TagStudioDev/TagStudio#175]
![image](https://github.com/TagStudioDev/TagStudio/assets/100530521/136034ac-07a7-4764-875e-242306ffccf4)

**Comment by yedpodtrzitko** [comment]
can you please provide any of the original images with each background color?

**Comment by DeLoR1AnEc** [comment]
![image](https://github.com/TagStudioDev/TagStudio/assets/100530521/2f1915ff-4984-4a77-bc95-3573312dd17b)
![image](https://github.com/TagStudioDev/TagStudio/assets/100530521/f2a614eb-dafa-460d-a468-cb3e9d31ae85)

**Comment by CyanVoxel** [comment]
> All images are png files with transparent background

We mean the original files themselves that are in your library, not just screenshots

**Comment by CyanVoxel** [comment]
I noticed that you were likely using default Minecraft assets, although I can't guarantee that I'm looking at the same exact files on my machine. Nevertheless when viewing the respective assets on my machine I don't encounter the same bug with these files:
![image](https://github.com/TagStudioDev/TagStudio/assets/46939827/86aecf1c-a521-4bdb-9967-ab165b823c72)

With that being said though, I did fine the effect on a few of them:
![image](https://github.com/TagStudioDev/TagStudio/assets/46939827/5bebd3ae-ab75-400f-8cea-01d9d7f377bf)

I've found that when I open the affected images (in this case with Affinity Photo) and resave them with no changes, the issue disappears. This leads me to believe that there is an issue with Pillow reading the alpha channel data from the compressed PNGs.
![image](https://github.com/TagStudioDev/TagStudio/assets/46939827/18fc4d2c-397a-4aac-bb90-4c6308f6d9e3)

**Comment by Gawidev** [comment]
That's funny, 
![image](https://github.com/TagStudioDev/TagStudio/assets/95928592/994fb86a-f9cc-45ee-8e0c-8d409e270a10)
I'm getting a gif, transparent background, displaying as red.
Also the preview seems to have the same red color that appears as a thin border.
![image](https://github.com/TagStudioDev/TagStudio/assets/95928592/8bf8d99e-d639-408c-98ae-3f48173fb904)
And after opening it in aseprite and re-saving it, it now displays the thumbnail background as black, and the same thin border on the preview, same black color.

**Comment by CyanVoxel** [comment]
Interesting, so I guess it affects more than PNGs. @Gawidev could you send me the original file of this GIF if you don't mind?

**Comment by DeLoR1AnEc** [comment]
Sorry, my bad. But yes, these indeed are minecraft default assets.
