### ISSUE TITLE
Plan to use raw files?

### ISSUE THREAD

**Issue by maplepy** [TagStudioDev/TagStudio#193]
Hello! Loved your video so much I had to check out your software, but I was wondering if there was plan to render raw files, (`.raw`, `.cr3`, etc.) 

Thank you very much :)

**Comment by CyanVoxel** [comment]
Thank you so much! 😁 And yes, support for this is already being [worked on](https://github.com/TagStudioDev/TagStudio/tree/raw-image-previews) and should be coming out in the near future!

Here's a screenshot of the different raw filetypes that I've confirmed to be working so far. Please let me know if there's any I'm missing, too!
![image](https://github.com/TagStudioDev/TagStudio/assets/46939827/c82751ef-abae-488b-907c-6298606da90e)

**Comment by maplepy** [comment]
Nice ! that's so great!

love you man ❤
