### ISSUE TITLE
[SUGGESTION/BUG] Tags not visible when none are searched

### ISSUE THREAD

**Issue by Maxello1** [TagStudioDev/TagStudio#2]
when adding a tag to an image and not searching for a tag explicitly, no tags are shown at all, i feel like it would be a cool idea to list all tags made by default into the Tag search with the scroll bar(depending on the amount of tags there is) and just secluding tags that dont fit the search anymore. (i hope that makes sense haha)

![image](https://github.com/CyanVoxel/TagStudio/assets/98433747/9a052197-4a95-434a-b884-983ac5454d0c)

**Comment by Wuffli** [comment]
We should also think about how the tags are sorted when not searching. Eg. having the ones which are used most being at the top for easy access. In a further step the sorting could be smarter eg. Taking into account what filetype the tag is attached to etc.

**Comment by CyanVoxel** [comment]
Tags are now shown by default as of #103. In the future there will be additional options shown in the "Add Tag" panel, including recently used and most used tags.
