### ISSUE TITLE
[Feature Request] Import tags from SD tagger

### ISSUE THREAD

**Issue by KisenaMiyuki** [TagStudioDev/TagStudio#203]
Wish we could import tags generated by Stable Diffusion tagger, so less hassle on manually adding them

**Comment by CyanVoxel** [comment]
There's currently some limited support for [sidecar](https://github.com/TagStudioDev/TagStudio?tab=readme-ov-file#gallery-dl-sidecar-importing) importing which will be rolled into an expanded generic data import system in the future.

I'm not sure what format SD tagger expects, but if it can export tags to a plaintext/JSON format that TagStudio could read then it should be possible with these systems, possibly even presently. If it requires any deeper integration than that then this would be best served as an external plugin down the line.
