### ISSUE TITLE
Multiple tag fields

### ISSUE THREAD

**Issue by K4gurai** [TagStudioDev/TagStudio#218]
![image](https://github.com/TagStudioDev/TagStudio/assets/66545654/dfe698e6-1ba7-4e86-a03c-b60ffefc425a)

I have some files that have multiple Tag fields.
It may have happened when I added a Tag field, deleted it, then added it back again.
As you can see, there's 3 tag fields. I added Tag fields thrice and deleted them twice.
I also have some files that only had 2 since I only deleted it once and added it twice.

I also tried to close and open the app again and it didn't fix it.

**Comment by CyanVoxel** [comment]
Is the issue that these extra tag fields are being spontaneously created and/or not being deleted properly? My hunch is that this is an extension of #92 which involves issues with multiple fields of the same type.

**Comment by CyanVoxel** [comment]
Unless there's any more details I'll have to assume that this is either working as intended or some interaction with #92
