### ISSUE TITLE
[BUG] Tagstudio crashes when clicking on a video that has no frames

### ISSUE THREAD

**Issue by Thesacraft** [TagStudioDev/TagStudio#252]
When clicking on a video that has no frames Tagstudio crashes.
Thats the video that crashes it:

https://drive.google.com/file/d/1PMB1wWUr9k8cWOzRGa2jpH14kCOIZJiF/view?usp=sharing
(i uploaded it to drive because i think you can't dowload it when its uploaded to github)

**Comment by Thesacraft** [comment]
Also there is no Error that is outputed to the console. And the thumbnail preview is also missing with the loading texture being there instead. 
![grafik](https://github.com/TagStudioDev/TagStudio/assets/91694323/23fb475b-5f7d-4f9d-a2b7-f06f7335d0de)

**Comment by Loran425** [comment]
Looks like cv2 defaults to not throwing exceptions. 
For discovery this can be changed by calling `video.setExceptionMode(True)`

This appears to be related to trying to read the file with 0 frames as video.read() will lag for 5+ seconds on my machine so I'm guessing something else errors out trying to wait for that. I'll toss together a quick PR that will just raise an error if the frame_count is 0 or -1 (returned on invalid files)

**Comment by CyanVoxel** [comment]
> Looks like cv2 defaults to not throwing exceptions. For discovery this can be changed by calling `video.setExceptionMode(True)`
> 
> This appears to be related to trying to read the file with 0 frames as video.read() will lag for 5+ seconds on my machine so I'm guessing something else errors out trying to wait for that. I'll toss together a quick PR that will just raise an error if the frame_count is 0 or -1 (returned on invalid files)

You know what, I was running into a similar issue with cv2/ffmpeg errors on the [`thumbnails`](https://github.com/TagStudioDev/TagStudio/tree/thumbnails) branch and ended up creating an [`is_readable_video`](https://github.com/TagStudioDev/TagStudio/blob/thumbnails/tagstudio/src/qt/helpers/file_tester.py) method for testing if a codec is valid before wasting time erroring out trying to render the thumbnail. It uses `ffmpeg.probe` to read the video metadata before attempting to send it off to cv2 to read, and I bet we could just put in an extra condition to check for the number of frames and consider that "unreadable".

**Comment by Loran425** [comment]
> You know what, I was running into a similar issue with cv2/ffmpeg errors on the [`thumbnails`](https://github.com/TagStudioDev/TagStudio/tree/thumbnails) branch and ended up creating an [`is_readable_video`](https://github.com/TagStudioDev/TagStudio/blob/thumbnails/tagstudio/src/qt/helpers/file_tester.py) method for testing if a codec is valid before wasting time erroring out trying to render the thumbnail. It uses `ffmpeg.probe` to read the video metadata before attempting to send it off to cv2 to read, and I bet we could just put in an extra condition to check for the number of frames and consider that "unreadable".

That would also work as long as that is_readable_video function is called in both the thumb renderer and the preview panel.

**Comment by CyanVoxel** [comment]
> That would also work as long as that is_readable_video function is called in both the thumb renderer and the preview panel.

It should be called in both. For now though I'm happy with your solution #275 and'll get that pulled soon
