### ISSUE TITLE
Im following the Launching Development Environment from Readme  while using nixos there is import method error

### ISSUE THREAD

**Issue by hemanth-92** [TagStudioDev/TagStudio#253]
while running the TagStudio.sh script it gives ImportError: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory

![image](https://github.com/TagStudioDev/TagStudio/assets/131354764/3591d273-0b78-438c-afe1-701f34d9a3ac)

**Comment by hemanth-92** [comment]
After looking into requirements.txt found that PySide6 is missing  **Added    python312Packages.pyside6**
in the flake.nix .  i ran TagStudio.sh again now it gave me **Fatal Python error: none_dealloc: deallocating None: bug likely caused by a refcount error in a C extension**

**Comment by seakrueger** [comment]
Add pkgs.libkrb5 to LD_LIBRARY_PATH. See 3e4a32cd31eb0ba026b31a00ecd8edc3774fb73a from #244. (Fixed in #244)

**Comment by xarvex** [comment]
Just reopening until that PR (or a similar) is merged in, just want to keep track. Appreciate the confirmation that the fix there is working.

**Comment by xarvex** [comment]
This should be fixed thanks to #244 being merged in, please reopen if this persists.
