### ISSUE TITLE
Parent Tag inheriting Child Tag's shorthand?

### ISSUE THREAD

**Issue by InfernoDigital** [TagStudioDev/TagStudio#254]
![image](https://github.com/TagStudioDev/TagStudio/assets/12396056/61c4b869-0a80-48a5-bf9d-7cd5698e9217)

Hi! I'm just getting started using TagStudio, and I know it's in Alpha, just putting this issue up because I'm unsure if this is the correct behavior or not, but it was a bit confusing to me as a user, so wanted to point it out.

I set up the "video games" tag with the shorthand "Gm" in the app, and then created two game subtags, "Infinity Blade" (INF) and "Minecraft" (MC). However, when I applied the first subtag to the parent tag, now the parent tag has "(INF)" next to it all the time, even when I'm wanting the picture to be tagged Video Games/ Minecraft.

Am I just using the system wrong or misunderstanding how the hierarchy system works, or is this a bug?

Appreciate the help, this system looks really powerful once you understand it.

**Comment by YoyloNerd** [comment]
It's a naming thing that is getting fixed in the newer releases the sub tag is getting renamed to parent tag since that's what it is

**Comment by CyanVoxel** [comment]
Yep, "Subtags" have been renamed to "Parent Tags" as of c75aff4db3edf2a2a1effd392c432b2cefdc9f7c to help avoid this confusion. Should be included in the next build!
