### ISSUE TITLE
Window size change causes unclickable images.

### ISSUE THREAD

**Issue by kimmustcode** [TagStudioDev/TagStudio#256]
When I make my window smaller, it causes a number of images from the bottom to not be clickable.

**Comment by CyanVoxel** [comment]
I've experienced this on occasion as well, but have never been able to reliably reproduce it.

**Comment by PeterBouSaada** [comment]
Does this happen when you resize horizontally, vertically, or both?

**Comment by CyanVoxel** [comment]
I'm relaying a report of this happening to someone when they resized the preview panel, at least confirming that this is an issue with the grid panel itself and not the window as a whole

**Comment by CyanVoxel** [comment]
I've now been able to consistently replace this issue by creating a library with exactly 312 items on screen and adjusting the grid view so that it's either 5 or 6 columns wide. In both cases only the first 44 rows of the grid are selectable.

**Comment by CyanVoxel** [comment]
I've found the issue. The invisible `ItemThumb` objects that get hidden from view when viewing a page with less than the maximum number of items would, under *very* specific circumstances, sometimes cover and block the mouse input of other `ItemThumb`s. I'm submitting a PR with a fix now.
