### ISSUE TITLE
[Bug]: Potential Progress Bar Occlusion?

### ISSUE THREAD

**Issue by Frooozeeen** [TagStudioDev/TagStudio#296]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.3.1

### Operating System & Version

Windows 11 Pro

### Description

while scanning for new directories the purple progress bar does not show while tabbed out of the app and hovering over Tagstudio.

### Expected Behavior

the progress bare should show

### Steps to Reproduce

refresh new directories

**Comment by CyanVoxel** [comment]
Could you attach a screenshot of the issue you're seeing? I'm not sure if you're referring to the progress bar being behind whichever window you switched to, or if it's behind the main TagStudio window itself, or some other scenario.

**Comment by CyanVoxel** [comment]
@Frooozeeen Any additional info on this?
