### ISSUE TITLE
[Bug]: File Paths not Intercompatible between Windows and Linux

### ISSUE THREAD

**Issue by coolesding** [TagStudioDev/TagStudio#298]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.3.1

### Operating System & Version

Windows 11 and Arch Linux

### Description

When copying the Tagstudio folder from Windows to Linux the Linux version can not open the Tagstudio Library properly due to the Windows version saving the path as `Subfolder\\File` using two backslashes, which the Linux version can't read properly.

Here is a screenshot of what the Linux device read.
![image](https://github.com/TagStudioDev/TagStudio/assets/71647195/ec588a9d-77d3-4c91-8bd0-6e77adafef2f)

Manually replacing `\\` with `/` fixes the issue on Linux and still works properly on Windows

We're in love with Bocchi

### Expected Behavior

Moving a Tagstudio Library between two different operating systems should open properly and work.

### Steps to Reproduce

1. Create a Tagstudio Library with subfolders on Windows and Tag files
2. Move the Tagstudio Library to a Linux system
3. Try opening the Tagstudio Library

**Comment by searinminecraft** [comment]
looks like if the database is moved to sql then this issue might (hopefully) be resolved? ill be patient though
