### ISSUE TITLE
[Feature Request]: Generate thumbnails and previews for font files (e.g., TTF, OTF)

### ISSUE THREAD

**Issue by olipra** [TagStudioDev/TagStudio#304]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

To streamline font management within TagStudio, I'd like to request the addition of a feature that automatically generates thumbnails and previews for font files. This feature would provide users with a visual representation of each font, making it easier to browse, select, and tag fonts.

### Solution

Right now, TagStudio shows the same file icon as the thumbnail of TTF and OTF files. TagStudio could generate font files thumbnails displaying a sample of the font (e.g., “ABC” or “Sample Text”) in a standardized size and format. Thumbnails are a must but previews would be a great addition too (but it would probably be harder to integrate in the interface). These previews would include various text samples, sizes, and styles, showcasing every aspect of the font which would make it easier to tag. Including the font's metadata (e.g., font name, style, weight) alongside the preview would also be great. [Eagle](https://en.eagle.cool/article/487-saving-fonts) manages this pretty well but TagStudio has a better tagging system and would be a great open-source alternative to many font managing apps which only work with sub-folders or have very clunky tagging systems.

**Comment by CyanVoxel** [comment]
Completed in #307 😁
