### ISSUE TITLE
[Bug]:  Warning when clicking away from a multi selection

### ISSUE THREAD

**Issue by Thesacraft** [TagStudioDev/TagStudio#305]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

source ( up to date )

### Operating System & Version

Windows 11

### Description

When selecting multiple entries and then selecting one entry a Warrning is thrown. This is because of the switch to Pyside6 v6.7.1

### Expected Behavior

Should not throw a Warning.

### Steps to Reproduce

1. Select multiple entries
2. Select one entry

### Logs

D:\Development\python\Tagstudio\small-bug-fix\tagstudio\src\qt\widgets\preview_panel.py:593: RuntimeWarning: Failed to disconnect (None) from signal "clicked()".
  self.preview_img.clicked.disconnect()

**Comment by CyanVoxel** [comment]
Fixed in #306
