### ISSUE TITLE
[Bug]: TagStudio does not run on Linux - "no Qt platform plugin could be initialized"

### ISSUE THREAD

**Issue by joshbuker** [TagStudioDev/TagStudio#312]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.3.1

### Operating System & Version

Pop! OS 22.04 LTS

### Description

See also #280 

When attempting to run the TagStudio binary, it fails to launch stating "This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem."

First, I tried the normal binary, then tried the portable binary. They are both affected, and both fixed with the same solution.

To fix, install `libxcb-cursor-dev`:
```sh
sudo apt install -y libxcb-cursor-dev
```

### Expected Behavior

Following the installation instructions in the README.md works.

Either the xcb library should be packaged with the binary, or instructions to install the library should be included in the README.md

### Steps to Reproduce

1. Download linux binary
2. Attempt to run the binary
3. Fails to start due to missing xcb library

### Logs

```
[ResourceManager] 4 resources registered
[QT DRIVER] Config File not specified, defaulting to [filepath]
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "[folder]" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, vkkhrdisplay, minimalegl, wayland-egl, vnc, xcb, linuxfb, minimal, wayland, offscreen.

[1]    7800 IOT instruction (core dumped)  ./tagstudio
```

**Comment by Qronikarz** [comment]
This appears to be the same issue, but I thought it was already fixed:
https://github.com/TagStudioDev/TagStudio/discussions/182

**Comment by xarvex** [comment]
There is nothing to fix here, Qt packages cannot be bundled with the binaries so as to interact with the system. Install the missing package and you will be able to run TagStudio.
This is my reminder though to actually put this in the readme.
