### ISSUE TITLE
[Feature Request]: Improve the Default Order of Tags When Adding

### ISSUE THREAD

**Issue by samuellieberman** [TagStudioDev/TagStudio#327]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

Currently, in the "Library Tags" and "Add Parent Tags" windows tags are sorted by creation date. I understand that there are a lot of improvements and long-term features being planned for tagging entries, but it would be nice to temporarily have a more helpful default ordering until these features are implemented.

![image](https://github.com/user-attachments/assets/adcdc7ea-d04a-4709-a42e-7fbd5688c1ee)

These kinds of perspectives are common when dealing with many tags with lots of different colors. Dealing with this kind of sorting is frustrating when the colors or names of the tags hold more meaning than the point in time at which they were added.

### Solution

My suggestion is to sort by tag color first, and then alphabetically within each color. Discord user Gibby9er9er0 has also expressed dissatisfaction at the default order of tags when adding them, and approved of my suggested ordering. I don't use `Archived` and `Favorite`, but I don't see any problem with them appearing at the top of the search regardless.

**Comment by samuellieberman** [comment]
Also, "Add Parent Tags" still exhibits the problem from issue #2. I wonder what's up with that.

**Comment by CyanVoxel** [comment]
Completed in #329
