### ISSUE TITLE
[Feature Request]: Drag-n-drop "to" and "from" app

### ISSUE THREAD

**Issue by Dott-rus** [TagStudioDev/TagStudio#335]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

1. Drag and drop files into app to add them to your library (folder).
2. Drag and drop a file from app (like how works in default File Explorer) (example: to upload it into Discord).

**Comment by CyanVoxel** [comment]
This feature has was requested in #75 and completed in #153, and will be included in the upcoming 9.4 release😁
