### ISSUE TITLE
[Bug]: Tag-studio breaks windows default photo viewer when trying to open an image with out an other instance of it already being open

### ISSUE THREAD

**Issue by Thecreatre** [TagStudioDev/TagStudio#339]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.3.2 & Alpha 9.3.1

### Operating System & Version

Windows 11

### Description

uh so for this  update and last update (9.3.1) (these are the only versions ive used)

if i try to open an image in the  photos app thing from  windows,  with out an instance  of it open already it will lock up, not open, and stop working until i force close it with task manager

i did notice that for Linux a similar issue showed up* how ever i thought i  might as  well make a windows version of the issue, cause it  might be different across OS's

*(in the issues category, i don't acculy use Linux)

### Expected Behavior

the file just opens in photos with out it locking up

### Steps to Reproduce

just either right click an image and click open file or click the small preview window 

and both will lock it up

### Logs

i would if i knew how

**Comment by Thecreatre** [comment]
huh after photos randomly updated its no longer occurring for me (maybe it  was just a problem w ith that one version of photos? no idea, ig ill update this issue if it comes back)

**Comment by CyanVoxel** [comment]
Is this issue still gone? Probably an issue with Windows Photos itself?
