### ISSUE TITLE
[Feature Request]: I would like to add a feature similar to AI prompt tags found in WEBUI and COMFYUI.

### ISSUE THREAD

**Issue by mayjack0312** [TagStudioDev/TagStudio#341]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

Automatically scan or capture the prompts in the images, using external WEBUI or COMFYUI for assistance. It would be fantastic if this could be done internally within the software.

### Solution

Use a local external WEBUI or COMFYUI service, or invoke related Python scripts within the software.

You can refer to this [issue](https://github.com/TagStudioDev/TagStudio/issues/326) simultaneously.

### Alternatives

——

**Comment by The-Stolas** [comment]
I agree that this would be really helpful. I don't think you need it to be tied to ComfyUI specifically, but any image interrogator compatibility would do wonders for those who use "booru" style tagging for their libraries. It really is a pain to add "1boy, 1girl, dark hair..." type of tags to every single image. 

I understand that implimenting full AI tagger support within the app is very complex, but those image interrogators produce plain text files with tags in them. So, just adding the ability to add tags to an image from a text file would really speed up the process.

**Comment by mayjack0312** [comment]
> I agree that this would be really helpful. I don't think you need it to be tied to ComfyUI specifically, but any image interrogator compatibility would do wonders for those who use "booru" style tagging for their libraries. It really is a pain to add "1boy, 1girl, dark hair..." type of tags to every single image.
> 
> I understand that implimenting full AI tagger support within the app is very complex, but those image interrogators produce plain text files with tags in them. So, just adding the ability to add tags to an image from a text file would really speed up the process.

If it can be achieved, then the implementation method would indeed become very convenient.

**Comment by CyanVoxel** [comment]
This is something I am not interested in adding into the program natively, as I explain in the [readme](https://github.com/TagStudioDev/TagStudio?tab=readme-ov-file#features-that-will-not-be-added). However, this could be done by someone in the future as a [plugin](https://github.com/TagStudioDev/TagStudio/issues/47).
