### ISSUE TITLE
[Bug]: Create Tags From Folders not working

### ISSUE THREAD

**Issue by BetOnJeanette** [TagStudioDev/TagStudio#346]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.3.2

### Operating System & Version

Arch Linux 

### Description

Attempting to use the "Create Tags From Folders" macro does not create the tags from the folders. The window does not close. 

### Expected Behavior

Applying the macro should result in the tags being created and applied to the files within the directory.

### Steps to Reproduce

1. Create a library in a directory that has subdirectories
2. Attempt to use the "Folders to Tags" macro
3. Click apply
4. Nothing happens for the end user.

### Logs

In the console from which I launched tagstudio: 

Converting folders to Tags
Traceback (most recent call last):
  File "src/qt/modals/folders_to_tags.py", line 235, in on_apply
  File "src/qt/modals/folders_to_tags.py", line 74, in folders_to_tags
  File "src/qt/modals/folders_to_tags.py", line 64, in add_folders_to_tree
KeyError: 'tag'

**Comment by CyanVoxel** [comment]
Thank you for the detailed report, I can confirm that this is reproducible. My hunch is that this is a regression introduced in #98 but I'm looking into it in more detail now

**Comment by Thecreatre** [comment]
yeah its never worked for me either
