### ISSUE TITLE
[Feature Request]: Tagging With Mixed Data

### ISSUE THREAD

**Issue by LexiTheTT** [TagStudioDev/TagStudio#362]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

In short, Just allowing for tags to be added to mixed data.
It'd make it less of a pain to work add tags in bulk.
![image](https://github.com/user-attachments/assets/3380791f-73bf-4a59-98c2-f72f070097cd)

### Solution

Keep the plus button under the fields.
If the tag is already there on one, just skip it and move on to add it to the next.

**Comment by LexiTheTT** [comment]
I understand you can add a new filed and then retag it but repetition and redundancy freaks out my autistic mind sometimes..

**Comment by coolesding** [comment]
YES PLEASE
