### ISSUE TITLE
[Feature Request]: Add preview for .mscz sheet music

### ISSUE THREAD

**Issue by Jollottaja** [TagStudioDev/TagStudio#363]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

Currently TagStudio shows .mscz files like so
![image](https://github.com/user-attachments/assets/a20bbe35-0fed-417f-9ce6-7a8f80e6ea54)

### Solution

However, as per the documentation on the .mscz file type:

"MuseScore format (*.mscz)

MSCZ is the standard MuseScore file format and recommended for most uses. A score saved in this format takes up very little disk space, but preserves all the necessary information. The format is a ZIP-compressed version of .mscx files and includes any images the score may contain and a thumbnail.

Note: An .mscz file can be unzipped using a ZIP software utility to extract an uncompressed .mscx file. (Note that changing the file extension from .mscz to .zip may be required to unzip the .mscz file, depending on the software utility used.)"

If a .mscz file is unzipped, then the thumbnail for that score can be found under <ScoreName>/Thumbnails/thumbnail.png
It would be nice for TagStudio to be able to access these thumbnails and show them as a preview, instead of the current blank file icon.

Python has a library called zipfile, which could be used to access the contents inside the archive, without the need to temporarily extract them.

**Comment by CyanVoxel** [comment]
Added in #366/#545
