### ISSUE TITLE
[Feature Request]: Thumbnails for PDFs

### ISSUE THREAD

**Issue by Heiholf** [TagStudioDev/TagStudio#374]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

Render first page of PDF as thumbnail.

### Solution

I can implement it myself, I just wanted to have a proper Issue so that the PR is not completely random.

Qt has PDF rendering functions, I would use those to prevent adding additional dependencies. 

### Alternatives

There might be faster PDF engines than the builtin in Qt. However, the speedup won't be gigantic and it is easier to use less dependencies.

**Comment by CyanVoxel** [comment]
PDF previews added in #543 (port of #378)
