### ISSUE TITLE
[Feature Request]: Remote Storage S3

### ISSUE THREAD

**Issue by adrian-goe** [TagStudioDev/TagStudio#376]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

It would be very handy to connect the library to a s3 Bucket in addition to a local file system or network storage. 
This would allow having "unlimited" storage for someone like a photographer or videographer.
Really nice would be local tagging and then uploading to s3.

### Solution

* add "enable s3" setting for one library
* * add bucketurl (to have options for example AWS s3, minio, gcp cloudstorage...), region, access & secret key and sync options
* scan s3 bucket for existing files
* upload files to s3 if option is enabled

Be aware, that there could be costs for s3 for uploading and downloading (previews/thumbnails) and there could be different storage classes like glacier.

**Comment by CyanVoxel** [comment]
As mentioned by Heiholf, this falls under the category of [features I will not add or pull](https://github.com/TagStudioDev/TagStudio?tab=readme-ov-file#features-that-will-not-be-added).
TagStudio is built to read locally mapped drives (included networked), and adding support for remote storage such as S3 buckets is unfortunately out of scope for what I'm willing to refactor for and upkeep.
