### ISSUE TITLE
[Bug]: Unable to Run the program in Windows 11 OS, after extracting

### ISSUE THREAD

**Issue by ShreyanshGitam** [TagStudioDev/TagStudio#396]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.3.2

### Operating System & Version

windows_x86_64 & windows_x86_64_portable

### Description

I am facing some trouble when trying out your software, I have tried installing both the available Windows versions, but none are working at all when I try to open them, my pc for some reason refuses to run them, I am getting no form of feedback trying to run it, it just makes my file explorer app turn white like when applications are lagging and stopped running, and then it turns back to normal, then its all there is, the app doesn't open, there's nothing running in the background, etc.

My device specs:
Lenovo Ideapad Gaming 3i
Intel-i5 11300H
Ram: 16GB DDR4
Intel(R) Iris(R) Xe Graphics
Nvidia Geforce GTX 1650
P.S. Both graphics cards have shared memory of 4GB
OS: Windows 11 (Updated from Win-10)
Date: 25-08-2024

### Expected Behavior

The program should be running normally with the Program Window opening as I had seen in the Video on Youtube. But it doesn't open at all, and nothing happens.

### Steps to Reproduce

I am not sure how well this could be reproduced, but what I did was,
1. Downloaded the '.zip' package from the Github Repo
2. After downloading, I moved it to another folder in C drive.
3. Then I extracted it with the default Windows 11 extracting tool, that's found in the right-click context menu.
4. Double-clicked to run, but it didn't work.
5. Right-clicked and 'Ran as Administrator', which also didn't work.

**Comment by CyanVoxel** [comment]
Thank you for the bug report! Is there any sort of antivirus you're running? Including Windows/Microsoft Defender? If so, check to see if it's blocking the program without notifying you

**Comment by CyanVoxel** [comment]
@ShreyanshGitam Any updates on this?

**Comment by grapt0lite** [comment]
@ShreyanshGitam What file did you run? You could either be running the wrong one, or

**Comment by ShreyanshGitam** [comment]
I have just now downloaded the most latest version & its working, and I am on my way to install ffmpeg, for a smoother experience, thanks a lot for your patience,

I am truly sorry for the delay in reply, I had gotten busy with exams!!
