### ISSUE TITLE
[Bug]: nav_forward button causes error when used.

### ISSUE THREAD

**Issue by D4nDude** [TagStudioDev/TagStudio#413]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha v9.3.2

### Operating System & Version

Windows 10

### Description

When attempting to use the nav_forward button in the UI, the function errors with the following error:

The function errors and does not update the UI, however the UI continues with its main loop. When trying to use the nav_backward button it functions as normal and lets you move backwards in tabs.

### Expected Behavior

When clicking the nav_forward button, the UI should advance to the next page.

### Steps to Reproduce

Method 1:
1. Open TagStudio and do not load a library.
2. Click the nav_forward button.

Method 2:
1. Load a library.
2. Click nav_forward.

### Logs

Traceback (most recent call last):
  File "C:\dev\TagStudio/tagstudio\src\qt\ts_qt.py", line 1008, in nav_forward
    self.update_thumbs()
  File "C:\dev\TagStudio/tagstudio\src\qt\ts_qt.py", line 1218, in update_thumbs
    if i < len(self.nav_frames[self.cur_frame_idx].contents):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'bool' has no len()

**Comment by yedpodtrzitko** [comment]
fixed in #332
