### ISSUE TITLE
[Feature Request]: Add the ability to reorder tags

### ISSUE THREAD

**Issue by coolesding** [TagStudioDev/TagStudio#432]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

This is another tag managing QOL feature. As described in #431 it would let users fix their misordered tags and group them more easily and replace the extremely tedious option we currently have of changing a tag to be a copy of the one you want to move and then retagging all images.

### Solution

You should be able to drag a tag in the Manage Tags window and have it reposition itself wherever you want

### Alternatives

I've already mentioned this above, you can either copy the data of the tag you want to move into another one and retag everything, or, when it gets released, you could use the deletion feature from #148 to do a similar thing, although this would also be horribly tedious, since in some cases you would have to delete almost all of your tags, depending where your tags are located and where you want to move them.

**Comment by CyanVoxel** [comment]
While versions before 9.4 used the default creation order, as of #329 (a part of 9.4 now) this tag ordering is done by alphabetical/color order. Would this be enough to satisfy for you use case for reordering tags here?

**Comment by Cool-Game-Gev** [comment]
@CyanVoxel While I cannot speak for @coolesding, I think it's great.

**Comment by CyanVoxel** [comment]
As things stand I'm afraid that tags on entries are not going to support a manual order. For the time being they'll continue to be sorted by alphabetical/natural sort order, however we may introduce other sort orders in the future.

For the Manage Tags pane + future comprehensive Tags Tab/Panel, this will also not support manual ordering but will definitely support several sorting and grouping orders (name, color, category, asc, desc, etc.)
