### ISSUE TITLE
[Feature Request]: Filter `images with no tags`

### ISSUE THREAD

**Issue by okuma10** [TagStudioDev/TagStudio#434]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

I don't think I saw this in the documentation nor the planned features(I might be wrong).
But at the moment(building a library folder) I find it useful to be able to filter images with `no tags`.

**Comment by CyanVoxel** [comment]
This feature is listed on the README under [Current Features](https://github.com/TagStudioDev/TagStudio?tab=readme-ov-file#current-features):
> - Search for entries based on tags, metadata (TBA), or filenames/filetypes (using `filename: <query>`)
> - Special search conditions for entries that are: `untagged`/`no tags` and `empty`/`no fields`.

"no tags" may not have worked when you tried it due to the bug in #112, but "untagged" will work just fine at the very least.

**Comment by okuma10** [comment]
Ah yes "untagged" worked Thanks!

**Comment by Thecreatre** [comment]
although ig something similar (as in sort by amount of tags) would be nice albeit that would probably prefer having its own whole issue made about it not just a comment in an invalid issue abt something else (maybe one exists already i dunno just getting stuff out of head)
