### ISSUE TITLE
[SUGGESTION] Be able to view unsupported filetypes, and open if a program is registered for them

### ISSUE THREAD

**Issue by lunathir** [TagStudioDev/TagStudio#44]
As title says. Currently files like shortcuts (lnk files) and music tracker files aren't visible and I'd love to be able to tag my software with tags like "utility" and "game" and whatnot, at least without having some sort of strange workaround.

**Comment by CyanVoxel** [comment]
There's plans to make the filetype system more flexible in this regard, allowing most files by default and then letting the user blacklist ones they don't want to see instead of the current whitelisting system

**Comment by CyanVoxel** [comment]
Also, just added support for shortcut files (no thumbnails currently) in 13c2ca1ea55cebb0b16977bf8e2b362710fe424f since I pretty much had the code already in there

**Comment by lunathir** [comment]
That makes sense, and thanks a lot for this! I just ran across this on YouTube yesterday and so far I think it's pretty neat.

**Comment by CyanVoxel** [comment]
- All file extensions are now supported along with a user-configurable blacklist as of 31f402289565b55d3a84d11f0eb6055e9bf42374
- The ability to open files and their locations via a context menu added in 5bd2aaaf9ec9b570db2a3021bf5024487c07d025 and 6831a8939277d211386c43189c26d69d0c7f39d5
