### ISSUE TITLE
[Bug]: No Video Thumbnails

### ISSUE THREAD

**Issue by Pepezaoo** [TagStudioDev/TagStudio#440]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.4.0

### Operating System & Version

Windows 10 Version 22H2 64-bit

### Description

![image](https://github.com/user-attachments/assets/33be3c25-caad-40a2-86eb-af42d1a135b0)

No Video preview/Thumbnail

### Expected Behavior

![image](https://github.com/user-attachments/assets/5a030d04-6751-4c4b-80a4-5b9d31e8a7f3)
( On a older version 9.3.0 )

### Steps to Reproduce

1. Open Tagstudio ( after updating to the newest version )
2. Noticed that the Video Thumbnails were gone ( initially tought they could be just loading but they never did )

**Comment by CyanVoxel** [comment]
Closing this out now that installing FFmpeg seems to have solved this issue 👍
