### ISSUE TITLE
[Feature Request]: Audio Playback

### ISSUE THREAD

**Issue by AwesomeParley** [TagStudioDev/TagStudio#450]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

Basically the same way that videos have playback when you press on them, audio should also playback. For right now, we have to press on the audio file, then press the icon on the right to open up another app to play the audio, instead, it should just play in the app.

**Comment by csponge** [comment]
Hi there!

I'm interested in this feature as well. I'll probably take a crack at implementing it, unless someone else has already done so.

**Comment by csponge** [comment]
Just wanted to give an update. I haven't forgotten about this!

I currently have audio files playing. I have a slider to change position, and buttons for play, pause, and mute.

There are a few more minor things to fix, but I'm hoping to have that done relatively soon.

After I get that all working, I think it would be cool to add a queue feature in. Not sure if that makes sense to include in this issue. Any thoughts on that?

**Comment by CyanVoxel** [comment]
> Just wanted to give an update. I haven't forgotten about this!
> 
> I currently have audio files playing. I have a slider to change position, and buttons for play, pause, and mute.
> 
> There are a few more minor things to fix, but I'm hoping to have that done relatively soon.
> 
> After I get that all working, I think it would be cool to add a queue feature in. Not sure if that makes sense to include in this issue. Any thoughts on that?

That sounds awesome! Not sure about a queue feature though, I feel that's outside the scope of the program. Playing back audio files is great for previewing but queues are more so the territory of a music player in my opinion.

**Comment by AwesomeParley** [comment]
> Just wanted to give an update. I haven't forgotten about this!
> 
> I currently have audio files playing. I have a slider to change position, and buttons for play, pause, and mute.
> 
> There are a few more minor things to fix, but I'm hoping to have that done relatively soon.

Awesome! I'm glad that it's being worked on and seems to be working for you. 

> After I get that all working, I think it would be cool to add a queue feature in. Not sure if that makes sense to include in this issue. Any thoughts on that?

I do agree that would be very cool, but seeing as CyanVoxel thinks it's outside the scope of the project, we can maybe wait a bit before adding that. I do believe it would be useful, but there's a lot of stuff we still have to do that's more important. 

Thanks for working on it!

**Comment by Cool-Game-Gev** [comment]
Is this resolved? If it is, I hate to be that guy, but you should close the issue

**Comment by CyanVoxel** [comment]
> Is this resolved? If it is, I hate to be that guy, but you should close the issue

There is a linked open pull request related to this issue (#529), and this feature request is not resolved until that or another PR that covers this issue is merged.

**Comment by Cool-Game-Gev** [comment]
@CyanVoxel Thank you!

**Comment by CyanVoxel** [comment]
Added in #576
