### ISSUE TITLE
[Feature Request]: A mass auto-add tag feature based on filenames.

### ISSUE THREAD

**Issue by ry10hu** [TagStudioDev/TagStudio#456]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [x] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

Similar to how you can manually add single tags to multiple selected files, but extracts the file extension, and adds tags based on that.

**Comment by Nginearing** [comment]
Hi, I would also consider joining the discussion at #437 as that feature would also as a result end up adding this feature at the same time.

**Comment by Tyrannicodin** [comment]
You can search `filename: .txt` or any other extension and that filters by extension
