### ISSUE TITLE
[Bug]: all files in all libraries are unlinked (red)

### ISSUE THREAD

**Issue by satorkain** [TagStudioDev/TagStudio#461]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/doc/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

alpha 9.4.0

### Operating System & Version

win 10

### Description

just downloaded and installed TagStudio. Created a new library in which for some reason the all files are unlinked. 

For example, just one music track in the new folder I just created in the root of the disc:

![изображение](https://github.com/user-attachments/assets/a7921ef3-2e08-4a35-a3cf-6a93f577279e)

And so with all libraries and all files. 

Experimenting, I found that only one folder with fonts opened without broken links.

fonts [Proxima Nova 2.zip](https://github.com/user-attachments/files/16906986/Proxima.Nova.2.zip) – files will be linked
track [ssssssssssss.zip](https://github.com/user-attachments/files/16907000/ssssssssssss.zip) – track will be unlinked

### Expected Behavior

there should be no unlinked files

### Steps to Reproduce

this Issue occurs with any folder... any newly created or added to TagStudio.

### Logs

where to find it?

**Comment by Nginearing** [comment]
> ### Logs
> 
> where to find it?

I assume to do debug mode you just run the exe from command prompt

> just downloaded and installed TagSpace.
TagSpace is it called? 😂😂

**Comment by satorkain** [comment]
although not all files in the library are red, e.g. pdf and txt. But mp3's are all red. 
Llibrary with more than 20 thousand files where mp3's are placed in different folders.

**Comment by Nginearing** [comment]
Copy paste all the stuff you see in the command prompt when you run the exe (from within the command prompt)

**Comment by Nginearing** [comment]
> > I assume to do debug mode you just run the exe from command prompt
> 
> ![изображение](https://private-user-images.githubusercontent.com/15098779/365156170-0bdc892d-f4ad-436e-ae58-972dcd272be8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MjQ2MzYsIm5iZiI6MTcyNTYyNDMzNiwicGF0aCI6Ii8xNTA5ODc3OS8zNjUxNTYxNzAtMGJkYzg5MmQtZjRhZC00MzZlLWFlNTgtOTcyZGNkMjcyYmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDEyMDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZWU1MWRhYTFlZTQ3ZTM0NWYwNWZkMTdlNWZkYzk0ZDllOGQ2OGNjMjg3ZjYzOGMwODdlYzAyZTlkYTI1ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0qSAoElA5kep8qsUa_NIZUTQpEHE4L7aYGkaC7wQVZo)
> ### ?

I guess that's not how it works on windows, I'm a Linux user sorry, let me just find out how to do it.

**Comment by seakrueger** [comment]
Where is tagstudio installed? Are you using the normal executable or portable one?

**Comment by satorkain** [comment]
> Where is tagstudio installed? Are you using the normal executable or portable one?

"d:/pro/TagStudio". At first I used a portable one, now I use normal.

**Comment by Nginearing** [comment]
> > Where is tagstudio installed? Are you using the normal executable or portable one?
> 
> "d:/pro/TagStudio". At first I used a portable one, now I use normal.

It could be a permissions error possibly? Can you try installing it on your C drive instead.

**Comment by Nginearing** [comment]
or just try using the one on D drive, but add files to your library that are located on C drive

**Comment by seakrueger** [comment]
Hi, do you have [FFmpeg](https://www.ffmpeg.org/) installed? 
If not, try installing and seeing if that resolves your issues. If you want to try an upcoming installing guide for the project: [Here](https://github.com/TagStudioDev/TagStudio/blob/a7d64ecdbe14685f7027efe41fb0dcd89c0bf23b/doc/utilities/ffmpeg.md#installation-on-windows)

**Comment by CyanVoxel** [comment]
For those unaware, this came from discussion #457

**Comment by satorkain** [comment]
> Hi, do you have [FFmpeg](https://www.ffmpeg.org/) installed?
Yes! everything pointed to this. After installing ffmpeg the problem was solved. Thanks!
