### ISSUE TITLE
[Feature Request]: .ORF file preview

### ISSUE THREAD

**Issue by NeedNot** [TagStudioDev/TagStudio#465]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

ORF files a type of raw image doesn't have thumbnail previews

**Comment by CyanVoxel** [comment]
Easy inclusion in 5995e4d416fb3f34dad5b93fd9c100fb506c5948, should be out in the next patch!
