### ISSUE TITLE
[Bug]: File creation date wrong

### ISSUE THREAD

**Issue by borlottie** [TagStudioDev/TagStudio#469]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

9.4.0

### Operating System & Version

MacOS 14.5

### Description

For many of my files, the listed creation and modification dates are seemingly in the wrong order, or further do not match what my file explorer lists for the same files.

TagStudio info panel - creation date (1 Sep 2024) is I think the date I moved the file into the directory? And modification date (11 Aug 2020) is on its own correct, but well before the file's listed creation date.
<img width="364" alt="Screenshot 2024-09-08 at 8 52 42 AM" src="https://github.com/user-attachments/assets/0283ecd4-04cd-4d99-a878-2d4def233e15">

Finder's info panel - showing creation date should be 31 July 2020
<img width="362" alt="Screenshot 2024-09-08 at 8 51 58 AM" src="https://github.com/user-attachments/assets/31b3d73e-8359-453c-8044-04dd6df2ed68">

### Expected Behavior

A file's listed modification date should be chronologically after its creation date, and both dates should match with the system's native file explorer.

### Steps to Reproduce

1. Move a file into the library folder
2. Select the file in TagStudio and inspect its listed creation date 
3. Compare with native file explorer's listed creation date

**Comment by CyanVoxel** [comment]
Is the Finder properties panel a screenshot of the file in the *exact* same location, or did you move/copy the file from iCloud Drive to your Documents folder for TagStudio?

If it was moved/copied then this could update the file's creation date, even if it's chronologically newer than the modification date. I often have this issue on Windows and a good chunk of my files have creation dates several years newer than their modification dates.

And if you're curious for technical reasons, TagStudio is reading from the files' `mtime` property for the date modified and its `ctime` for date created.

**Comment by borlottie** [comment]
The properties panel is the file in the exact same location - I accessed the finder file by clicking the filepath in tagstudio to reveal in finder.

**Comment by CyanVoxel** [comment]
Upon further research it appears that macOS uses the `birthtime` stat to store a more accurate creation date rather than Windows which uses the `ctime` (change time). This person explains it in more detail: https://stackoverflow.com/a/39501288

This should mean that this is fixable though, as we can just pull from the `birthtime` on macOS and continue to use `ctime` elsewhere.

**Comment by CyanVoxel** [comment]
Fixed in #472, will come in the next patch (v9.4.1)
