### ISSUE TITLE
[Bug]: Crash when closing program without an open library

### ISSUE THREAD

**Issue by Leseratte10** [TagStudioDev/TagStudio#480]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Fork of TagStudio 9.4.0 (see #479) to support Ubuntu 20.04

### Operating System & Version

Ubuntu 20.04

### Description

I noticed that when I open TagStudio and then close it again without creating a library, it crashes. Same goes when I click File -> Close Library. 

### Expected Behavior

Trying to close a nonexistant library shouldn't crash the program.

### Steps to Reproduce

1. Open program without a library defined. 
2. Either click File -> Close Library or just close the program. 
3. Notice exceptions / crash in the log.

### Logs

```
$ ./tagstudio 
2024-09-09 19:21:46 [info     ] resources registered           count=4
2024-09-09 19:21:46 [info     ] Config File not specified, using default one filename=/home/myusername/.config/TagStudio/TagStudio.ini
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load OpenSsl library
2024-09-09 19:21:48 [info     ] update_widgets                 selected=[]
Traceback (most recent call last):
  File "src/qt/ts_qt.py", line 326, in <lambda>
  File "src/qt/ts_qt.py", line 571, in close_library
AttributeError: 'Library' object has no attribute 'library_dir'


Traceback (most recent call last):
  File "tag_studio.py", line 66, in main
  File "src/qt/ts_qt.py", line 491, in start
    self.shutdown()
  File "src/qt/ts_qt.py", line 556, in shutdown
    if self.lib and self.lib.library_dir:
                    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Library' object has no attribute 'library_dir'

TagStudio Frontend (Qt) Crashed! Press Enter to Continue...
QThread: Destroyed while thread is still running
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by CyanVoxel** [comment]
This does not seem like a v9.4 log, this looks like it's from `main` which is based on v9.3.x and has recently had an initial SQL conversion pulled into it (#332).

See the blurb at the top of the [README](https://github.com/TagStudioDev/TagStudio) and in the [CONTRIBUTING.md](https://github.com/TagStudioDev/TagStudio/blob/main/CONTRIBUTING.md):

> [!CAUTION]
> **As of Pull Request [#332](https://github.com/TagStudioDev/TagStudio/pull/332) (SQLite Migration) the `main` branch will be an open test bed to get full JSON to SQL parity operational.** Existing TagStudio libraries are not yet compatible with this change, however they will **NOT be corrupted or deleted** if opened with these versions. Once parity is reached and a stable conversion tool in place, this notice will be removed.
>
> For the most recent stable feature release branch, see the [`Alpha-v9.4`](https://github.com/TagStudioDev/TagStudio/tree/Alpha-v9.4) branch. These v9.4 specific features are currently being backported to the SQL-ized `main` branch.

This is the best I've been able to make contributors coming from GitHub aware of this change and the state of the branches, however it can still be missed. It's easier to keep people in the loop over in the [Discord server](https://discord.com/invite/hRNnVKhF2G) where I post important updates and announcements to the for things like this, and keep important events like branch changes or impeding refactors pinned in the #tagsdtudio-dev channel.

**Comment by Leseratte10** [comment]
Oh damn. I did read that note about the SQL migration but missed the part about main not being the most recent branch. I will re-test with the Alpha-v9.4 branch and report back.

**Comment by Leseratte10** [comment]
Can no longer reproduce with the actual v9.4, sorry for the unnecessary report.
