### ISSUE TITLE
[Bug]: Directory refresh ignores search query

### ISSUE THREAD

**Issue by MichaelBrunn3r** [TagStudioDev/TagStudio#482]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.4.0

### Operating System & Version

NixOS 24.05

### Description

If the displayed images are filtered (i.e. only matching images are shown) and then the directories are refreshed, all images are shown. 

After every refresh, ALL thumbnails are regenerated. Thumbnail generation is already slow for me, so this makes adding images 1-by-1 very unpleasant. I thought I could fix this by just entering the query `untagged` which now only generates thumbnails for new images. But the refresh behavior makes this hack useless.

### Expected Behavior

Refreshing directories does not clear the search query, so I would expect that it is immediately applied after refreshing. Right now I have to press enter in the search query bar again after every refresh.

E.g. if I have the query `untagged` and it shows 10 images, I add an image to a folder, I refresh: Now 11 images are shown. But in reality all my images are shown.

### Steps to Reproduce

1. filter displayed images (e.g. `untagged`)
2. (Optional) add an image to a directory in the library
3. Refresh directories `Ctrl + R`

**Comment by seakrueger** [comment]
Fixed as part of SQL migration on main. I would not recommend switching to main as of right now though, there's no migration and "untagged" is not implemented yet, but the next major release (v9.5) should have the fix to this.

**Comment by MichaelBrunn3r** [comment]
Thx for the info. I'm looking forward to `v9.4`, thanks for the awesome work

**Comment by seakrueger** [comment]
Hey btw, turns out it's a single line to fix on the current 9.4 branch.
Assuming you're running from source since on nix, change [line 1094 of ts_qt.py](https://github.com/TagStudioDev/TagStudio/blob/Alpha-v9.4/tagstudio/src/qt/ts_qt.py#L1094) to `r.done.connect(lambda: (pw.hide(), pw.deleteLater(), self.filter_items(self.main_window.searchField.text())))`

**Comment by MichaelBrunn3r** [comment]
Wow, that fixed it immediatelly. Thx again
