### ISSUE TITLE
[Bug] Text is unreadable when windows is set to light mode

### ISSUE THREAD

**Issue by DiffDoff** [TagStudioDev/TagStudio#5]
Pretty sure this is due to improper handling of dark mode

**Comment by CyanVoxel** [comment]
Mostly fixed in d974aa777ced011a3fb57bf56a07cccdb1c7dafc. The "Add Fields" button still doesn't change with the theme, but should be legible enough for now. Assets such as the loading thumbnails also need to be updated to be more visible in light mode.
