### ISSUE TITLE
[Bug]: Tags with existing names can be created

### ISSUE THREAD

**Issue by vyshnav-vinod** [TagStudioDev/TagStudio#504]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.4.1

### Operating System & Version

Windows 11

### Description

We can create a tag with the same name for any number of times. I tried this with the latest release (Alpha 9.4.1) and also the `main` branch.  In the `Alpha` version, this is the result
![image](https://github.com/user-attachments/assets/f2dec054-33c2-47b6-89fa-eb44312d3b2c)
There should be some sort of check to prevent this. 

Also in the `main` branch, since SQL is being used and an `UNIQUE` constraint is given to the `tag name` column, the duplicate tag wont be created, but the user will not be notified of why it was not created. Some sort of a dialog box saying `Tag name already exists`  can help solve this. I can try to work on this, but where should I implement it? In the `main` branch or in the `Alpha` branch?

### Expected Behavior

Tags with existing names should not be created. A dialog box saying 'Tag already exists' or something should be shown to the user.

### Steps to Reproduce

1. Create a tag
2. Create another tag with the same name

**Comment by CyanVoxel** [comment]
This is intended functionality. One of the core aspects of the TagStudio tagging system is that tags are not restricted in the way traditional string tags are - one of these restrictions being unique names.

Tags in TagStudio are not identified via their name, and are instead objects containing several pieces of data. This includes several name aliases that do not need to be unique across other tags. Attributes in real life often have overlapping names, so TagStudio reflects that. There are other ways to distinguish between tags including tag colors and subtags which add an automatic "(Subtag Name)" to the end of tags for clarification.
