### ISSUE TITLE
[Feature Request]: Minecraft Skin Preview

### ISSUE THREAD

**Issue by AstroSquared** [TagStudioDev/TagStudio#519]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

It would be a nice addition to be able to render the 3D previews of Minecraft skins instead of showing just the skin file itself. 
As of right now (tested on latest alpha and couldn't find anything in commits), only the skin file is shown, which makes skins somewhat hard to recognize.

### Solution

I propose that Tag Studio should show a rendered skin in both the gallery grid and the details section on the right. The skin file could also be showed in the details section if desired.

### Alternatives

I could not think of other workarounds or alternatives other then keeping the current behavior.

**Comment by Nginearing** [comment]
Personally, I don't see it as feasible to add things like this just for one or two users to actually end up using it, it will likely have to wait until addon/plugin support is added.

**Comment by CyanVoxel** [comment]
Thank you for the feature request! However I agree with Nginearing here: this feature is very specific to a small set of users, and outside of the scope of what a core feature should be in my opinion. Since Minecraft skins are just normal .png files, there would need to be some sort of general option for displaying any kind of .png as a Minecraft skin, which would be messy from both a developer and a user standpoint.

Once plugins are a thing way down the line though, I could see this being a good use for that!

**Comment by Cool-Game-Gev** [comment]
@CyanVoxel I agree, plugins will be great!

**Comment by myxxmikeyxx** [comment]
Plugins with good support documents are important, but if plugins are added I would imagine someone could make that in a plugin, make make a plugin that tweaks [this github](https://github.com/bs-community/skinview3d)

**Comment by AstroSquared** [comment]
> Plugins with good support documents are important, but if plugins are added I would imagine someone could make that in a plugin, make make a plugin that tweaks [this github](https://github.com/bs-community/skinview3d)

this looks like a JavaScript library, and this project is currently written in python, so that library probably won't work.

**Comment by AstroSquared** [comment]
closing this issue because it's tagged as wontfix. I will probably reopen this as a plugin request once plugins are implemented.
