### ISSUE TITLE
[suggestion] custom fields

### ISSUE THREAD

**Issue by goldstargloww** [TagStudioDev/TagStudio#54]
i don't know enough about the details of how tagstudio works to know how easy this would be, but the ability to make custom fields is a thing i've seen before and i think it'd be nice to have

essentially just the ability to make your own fields and give them their own type (text/number/date/list/etc)

**Comment by CyanVoxel** [comment]
Yep, this is already on the Priority Feature list in the README! Definitely intend on having this feature

**Comment by goldstargloww** [comment]
got it, alright :D must've missed that lol, i did read and check for it

**Comment by CyanVoxel** [comment]
Closing this in favor of keeping track of it in #18
