### ISSUE TITLE
[Bug]: Image dimensions do not show in Preview Panel

### ISSUE THREAD

**Issue by CyanVoxel** [TagStudioDev/TagStudio#550]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.5.0 (main)

### Operating System & Version

Windows 10

### Description

The image dimensions are currently missing from the preview panel:
![image](https://github.com/user-attachments/assets/80ec0ed1-08fb-4a40-bbfc-d8bbe921b4aa)

### Expected Behavior

The image height and width dimensions in pixels should be displayed under the file type and file size labels. This currently still works for video files. Example running TagStudio Alpha v9.4:
![image](https://github.com/user-attachments/assets/38799b85-3dc0-4a7a-a77a-0c2c51d4a7b3)

### Steps to Reproduce

Click on an image in your TagStudio library to preview it, then observe the missing image dimensions.

**Comment by Roc25** [comment]
Found where problem. Error in if statement
![image](https://github.com/user-attachments/assets/c9608791-27d3-4f53-a18c-77d1b96c91cf)
