### ISSUE TITLE
[Development Feature Request]: Set function complexity and lenght limit

### ISSUE THREAD

**Issue by Roc25** [TagStudioDev/TagStudio#552]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

I know this is a very controversial topic and I'm not an expert on this, but 100+ line functions can sometimes be quite difficult to read.

Let me know if I'm wrong somewhere

### Solution

Set a limit on the length and complexity of a function using a linter 

### Alternatives

Do nothing

**Comment by CyanVoxel** [comment]
I feel setting an arbitrary method limit in the linter would just cause immediate extra work for us to refactor existing methods (especially long UI init methods) without providing much if any tangible benefit to the project. The project is also at a stage where the burden of refactors has been doing more harm than good as this actively stops us from fixing bugs and developing new features in favor of moving code around.
