### ISSUE TITLE
[Feature Request]: change images on pressing the mouse instead of on releasing

### ISSUE THREAD

**Issue by BPplays** [TagStudioDev/TagStudio#555]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

when i press my mouse down when selecting an image it doesn't select until i release, and holding doesn't seem to serve a function, so it adds an extra delay for no reason.

**Comment by Roc25** [comment]
I have implemented this functionality, but I think it is better to move this into separate settings, since not all users may like it. You can test it [here](https://github.com/Roc25/TagStudio/tree/press-select-instead-release)

**Comment by CyanVoxel** [comment]
A click-and-drag and/or box select function would give this more purpose, but I have no issue with this idea as it stands
