### ISSUE TITLE
[BUG] Removing Tag Field with Favorite/Archived Tag Doesn't Update Thumbnail Badges

### ISSUE THREAD

**Issue by CyanVoxel** [TagStudioDev/TagStudio#56]
### System Details
System: Windows 10 22H2
TagStudio Version: ff488da6c8cdf4b5f566f8a1122cfab69d577425

### Describe the Problem
When removing a tag field that contains either a "Favorite" tag or "Archived" tag from an entry, its respective icon badge over its library thumbnail is not updated.

### Steps to Reproduce
Same as above.

**Comment by Thesacraft** [comment]
This issue can be closed, because the bug got fixed
