### ISSUE TITLE
[Feature Request]: Ability to add new tags from within tag management.

### ISSUE THREAD

**Issue by Hissymaster** [TagStudioDev/TagStudio#565]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

Allow users to add new tags from within tag management by adding a + button to "Library tags" menu
This is intended to be a quality of life improvement.
this allows users to immediately check on their tags or more quickly make new tags.

### Alternatives

_Make Ctrl+T work within the Library tags menu._
Advantages: A keyboard shortcut is even faster than clicking a button, and even better for keyboard based workflows.
Disadvantages: Not very friendly to new users.

**Comment by CyanVoxel** [comment]
Sounds good to me! I also didn't realize that Ctrl+T doesn't function with the tags menu open, so yeah both of those options sound great.
