### ISSUE TITLE
[Feature Request]: Instant/Convenient Playback for Audio

### ISSUE THREAD

**Issue by AudleStudios** [TagStudioDev/TagStudio#568]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

In any DAW, an audio browser lets you tap a sound to play it instantly. Currently in Tag Studio, you have to open the file manually.

### Solution

Adding a play button to each icon, placing it next to the archive option, and turning the play button to a pause button when pressed.

![image](https://github.com/user-attachments/assets/f1f7bcb3-3862-4031-bf4e-b8bde66f0a51)

(This would probably have to added after built-in audio playback is)

### Alternatives

Placing it on the right half of each icon (on-hover)
![image](https://github.com/user-attachments/assets/f0545cfb-a516-4720-bd96-945cd84e7399)

Adding on to the first solution, adding a stop button, which would stop playback, and start the playback from the beginning when play is pressed again. 

![image](https://github.com/user-attachments/assets/0d42960a-932d-4ee8-befd-10ecbffbad6e)

or

![image](https://github.com/user-attachments/assets/28fa1396-1173-433b-acb5-b4a0c5ff3198)

**Comment by CyanVoxel** [comment]
Thank you for the feature request! While TagStudio is far from a DAW, we would like to at least have basic audio playback to aide with file classification and discovery (under the umbrella of audio browser, I suppose).

Currently we're planning on delegating audio playback to the Preview Panel, with #450 being the open issue for it and #529 being the last PR opened for it, however that PR was recently accidentally closed and I believe @VasigaranAndAngel has been prototyping a separate audio player that does not have an open PR at the moment, but adds a playback scrubbing tool over the audio waveform in Preview Panel.

Both of the above in-progress implementations follow the pattern of the Preview Panel being used for playback and in-depth previews of files, which is where I would personally like to keep this sort of functionality. I don't believe that this would be too disruptive to tagging and browsing workflows, and would make both the development of audio playback and the continued development of the thumbnail widgets *significantly* easier going forward.

If you're satisfied with this approach or have a compelling use case for having audio previews outside of the Preview Panel (that's also in the scope of the program) then I'll be more than happy to keep this request open.

**Comment by Cool-Game-Dev** [comment]
I like the top option the best, no need to make it complicated.

**Comment by CyanVoxel** [comment]
Audio playback for the preview panel added in #576 (formally #529)
