### ISSUE TITLE
[Bug]: Tag names have to be unique in > 9.4.1

### ISSUE THREAD

**Issue by Tishj** [TagStudioDev/TagStudio#571]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.5

### Operating System & Version

Windows

### Description

As noted by the response to #504 tag names didn't have to be unique

In the move to the SQLite db backend, the schema of `tags` enforces the name to be unique, breaking backwards compatibility with the old JSON backend

### Expected Behavior

Tags should be able to have duplicate names

### Steps to Reproduce

.

**Comment by CyanVoxel** [comment]
Fixed in 9c146510182ca3a6d3f739e35392a4fb68c647c0 on the [`json-to-sql`](https://github.com/TagStudioDev/TagStudio/tree/json-to-sql) branch. Will close issue once it's merged into `main`.

**Comment by CyanVoxel** [comment]
Fixed in #604
