### ISSUE TITLE
[Bug]: Program Warns Me abt ffmpeg not installed on the path yet it is on the path

### ISSUE THREAD

**Issue by hammouda101010** [TagStudioDev/TagStudio#578]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Most Recent Version

### Operating System & Version

Windows 11

### Description

program warns me abt FFmpeg not installed yet i followed all steps to make it run proprely

### Expected Behavior

no warnings should be found

### Steps to Reproduce

i have no idea what im doing

### Logs

![Screenshot 2024-11-07 111131](https://github.com/user-attachments/assets/88483874-a179-4ccb-b51d-9c76cfab13eb)

**Comment by maopequena** [comment]
@hammouda101010 how did you fix it? Can you please provide a more detailed explanation?

**Comment by seakrueger** [comment]
@maopequena If your tagstudio installation is failing to find FFmpeg try following the guide available [here](https://docs.tagstud.io/help/ffmpeg/), and if that does not work I'd recommend either adding more details here or (I'd recommend) joining the Discord server

**Comment by maopequena** [comment]
Thank you. I'll try that.

**Comment by jess2obsess** [comment]
for anyone else who comes along, I was getting this error and looking for a solution, but just restarting the program (for i guess the 3rd or 4th time) fixed it
