### ISSUE TITLE
[Documentation]: Inconsistent ruff behavior on Linux

### ISSUE THREAD

**Issue by python357-1** [TagStudioDev/TagStudio#580]
**Description**

In CONTRIBUTING.md, the following instructions are included for how to run ruff locally:

> Lint code by moving into the `/tagstudio` directory with `cd tagstudio` and running `ruff --config ../pyproject.toml`.

When running this on my machine on commit 2767daf, I get the following output (just using grep to make the output shorter):

![image](https://github.com/user-attachments/assets/c61ebc1f-9b60-4856-9d33-b31346fbf966)

However, this commit just ran through CI and only had 1 error. If I instead move one directory up and run `ruff check --config pyproject.toml`, I get the correct output:

![image](https://github.com/user-attachments/assets/c9c11659-e404-4741-a735-a10ea904ebd6)

**Solution**
This is probably just a bug in ruff. For the meantime, though, it probably wouldn't be a bad idea to include something about this in CONTRIBUTING.md for linux users.

**Versions**

- Linux 6.11.3

- Ruff 0.7.2

**Comment by CyanVoxel** [comment]
I just realized that I don't use this first step given in the CONTRIBUTING.md:
> Lint code by moving into the /tagstudio directory with cd tagstudio and running ruff --config ../pyproject.toml.

I may have made the assumption that the config file needed to be passed at least once in order for Ruff to use it on successive runs of `ruff format`, however according to the [Ruff docs](https://docs.astral.sh/ruff/configuration/#config-file-discovery) (and my own experience of completely forgetting about this) it seems that Ruff tries to automatically find the closest config file in the hierarchy. Furthermore, trying to follow this step on my Windows machine (ruff 0.6.3) I get the error "error: `ruff <path>` has been removed. Use `ruff check <path>` instead.".

So when I use Ruff, I'm simply running `ruff format` from the base repo directory. Nowadays we also have the added `ruff check` step which should be added to the CONTRIBUTING.md regardless. Let me know if running Ruff like this works as expected for you.

**Comment by seakrueger** [comment]
I have always run simply `ruff format`  from the base directory and it seems to work. Its using the config as it successfully handled reformatting following the recent ruff style changes. - On linux via the nix flake

**Comment by python357-1** [comment]
running just `ruff check` does automatically find the config. i guess i could update my PR to instead say that you should just run `ruff check` and trying to specify the config file if you aren't in its directory will make it not use it

**Comment by CyanVoxel** [comment]
> running just `ruff check` does automatically find the config. i guess i could update my PR to instead say that you should just run `ruff check` and trying to specify the config file if you aren't in its directory will make it not use it

What about `ruff format`? Both `ruff check` and `ruff format` are used in the [CI job](https://github.com/TagStudioDev/TagStudio/blob/main/.github/workflows/ruff.yaml)

Assuming both work, we should update the documentation to list both of those steps. We can recommend users to remain in the root directory but point them to the relevant ruff docs if they'd like to know more about how the config discovery works https://docs.astral.sh/ruff/configuration/#config-file-discovery

**Comment by seakrueger** [comment]
The current contributing file already says just to run `ruff format` https://github.com/TagStudioDev/TagStudio/blob/main/CONTRIBUTING.md?plain=1#L96

**Comment by python357-1** [comment]
for some reason ruff format works whether you specify the config file or not

**Comment by CyanVoxel** [comment]
> The current contributing file already says just to run `ruff format` https://github.com/TagStudioDev/TagStudio/blob/main/CONTRIBUTING.md?plain=1#L96

Yes that part will stay, but it needs to be updated to include the new `ruff check` step that was added in a recent CI change, and the step with the `cd` and `--config` is seemingly not needed.

**Comment by python357-1** [comment]
i was thinking we just replace line 95 and 96 with this:
```
- Lint code with `ruff check` and format code with `ruff format` inside the repository directory.
- There is seemingly a bug with `ruff check` that will sometimes cause it to not use the correct configuration if you DO specify the configuration file. For more information, see the [ruff configuration discovery docs](https://docs.astral.sh/ruff/configuration/#config-file-discovery).
```

**Comment by CyanVoxel** [comment]
> i was thinking we just replace line 95 and 96 with this:
> 
> ```
> - Lint code with `ruff check` and format code with `ruff format` inside the repository directory.
> - There is seemingly a bug with `ruff check` that will sometimes cause it to not use the correct configuration if you DO specify the configuration file. For more information, see the [ruff configuration discovery docs](https://docs.astral.sh/ruff/configuration/#config-file-discovery).
> ```

Do we really need to warn of a potential bug with ruff when we're not even instructing the user to use that flag anymore though? Seems like a couple steps removed from our jurisdiction here

**Comment by python357-1** [comment]
for users that are using the old command it could be helpful, but we can just link to the docs if you want

**Comment by CyanVoxel** [comment]
> for users that are using the old command it could be helpful, but we can just link to the docs if you want

I think the link should be sufficient for people who want to learn more about how the config is discovered. If anyone is actually using the `--config` flag each time and then rereads the contributing.md file, they would now see that we don't tell them to do that anyways. If they insist on using the `--config` flag despite reading these updated and clearer instructions then it's out of our hands if they run into any potential issues with ruff

**Comment by python357-1** [comment]
i just updated the PR with the new lines
