### ISSUE TITLE
[Bug]: Some tags show up in tag library, but not in tag box (unless you search for them)

### ISSUE THREAD

**Issue by GreyLight02** [TagStudioDev/TagStudio#630]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha 9.4.2

### Operating System & Version

Windows 11

### Description

I've been adding (a lot) of tags to my tag library, and when I went to actually add them to a file, I noticed that the list in the tag library does not match the tag box (in other words, some tags are invisible unless you search for them).

### Expected Behavior

I would like the list of tags in the tag library and in the tag box to match. It's frustrating to add a tag and then forget it exists because you have to search for it.

### Steps to Reproduce

Honestly, I don't know. Perhaps it's because I have a lot of tags. But it was like after a certain number they just stopped showing up in the tag box list.

**Comment by python357-1** [comment]
Would you be willing to share your ts_library.json file, or say how many tags that entry is supposed to have according to that file?

**Comment by CyanVoxel** [comment]
This is working as intended. The tag search boxes currently limit the number of tags shown to [100](https://github.com/TagStudioDev/TagStudio/commit/6a680ad3d18b0c7f2250870e98842b3e13c967b0) for performance reasons. #227 was originally the issue for this but seems to have been wiped from the face of the Earth.

**Comment by GreyLight02** [comment]
Ah. I see. I guess I went a little too crazy with the tags then... lol. Maybe sometime in the distant future an advanced setting to adjust this might be nice, but I imagine it's very low priority right now.
