### ISSUE TITLE
[Feature Request]: Improve migrating of Qt version

### ISSUE THREAD

**Issue by un-pogaz** [TagStudioDev/TagStudio#636]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### Description

[Forward feature for plugins]

Add a implementation to prevent plugin to break when changing of Qt version.

So, if TagStudio change of Qt version, migrate the import of the main app is normaly not a issue, but things become incredibly complex if you decide to implement a third-party plugin system, because third-party plugins are not updated at the same time as TagStudio.

If TagStudio change of Qt version, all the third party plugins will immediately stop working when the user will update TagStudio, as they will not be able to import the previous version of Qt implementation.

<br>

So, Yes, the plugins are far from being here, but I think that sooner we implement this feature, sooner we'll have solved a huge problem before *when* it will happen.

### Solution

Their is many way to solve this, but we can learn for our elder: [Calibre](https://github.com/kovidgoyal/calibre) (by Kovid Goyal) is a very honorable Python/Qt open sources project who lived across 3 Qt version (Qt4 -> Qt5 -> Qt6).

I recomend to implement the same solution as Calibre: a Qt Wrapper that is used instead of the default Qt import. See #637.

**Comment by CyanVoxel** [comment]
Closing for reasons explained here: https://github.com/TagStudioDev/TagStudio/pull/637#issuecomment-2537483158
