### ISSUE TITLE
MacOS install docs

### ISSUE THREAD

**Issue by odama626** [TagStudioDev/TagStudio#643]
I'm pretty sure you can get around the unidentified developer issue you command right clicking on the app and opening anyway. I don't have a chance to verify right now.

**Comment by odama626** [comment]
It'll be much easier than what's suggested.![Screenshot_20241214-102105.png](https://github.com/user-attachments/assets/3bfe7204-c00d-4df1-a451-30eb5ce98c0d)

**Comment by CyanVoxel** [comment]
As of macOS 15 Sequoia this workaround no longer works, and unfortunately you need to go through the whole process described in the docs.

https://hackaday.com/2024/11/01/apple-forces-the-signing-of-applications-in-macos-sequoia-15-1/

https://www.reddit.com/r/mac/comments/1ekv55h/cant_right_click_open_app_on_macos_sequoia/

**Comment by odama626** [comment]
Wow. That's awful of Apple

**Comment by CyanVoxel** [comment]
Yeah it's real unfortunate... Glad software like this can still be ran without the notarization process, but it sure does make it much more inconvenient.
