### ISSUE TITLE
[Bug]: Pressing Enter/Return no longer adds searched tag to entry

### ISSUE THREAD

**Issue by CyanVoxel** [TagStudioDev/TagStudio#645]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

Alpha v9.5.0 (main branch)

### Operating System & Version

Window 10

### Description

When in a tag search panel, pressing the enter/return key no longer adds that tag to an entry before closing the panel.

### Expected Behavior

In previous versions, the top tag result in a tag search panel would be added to an entry upon pressing the enter/return key.

### Steps to Reproduce

1. On an entry with a tag field, press the "+" button to open the tag search panel
2. Type in the full or partial name of a tag to add
3. Press the enter/return key
4. Observe how the panel closes, yet does not add the tag as it would in previous versions (guaranteed 9.4.x)

**Comment by SkeleyM** [comment]
i'd like to work on this
