### ISSUE TITLE
Add Previews (Thumbnails) For More File Types

### ISSUE THREAD

**Issue by Icosahunter** [TagStudioDev/TagStudio#65]
PDFs and SVGs are the ones I'd like to see the most, but I'm sure there are a lot of others.
[preview-generator](https://pypi.org/project/preview-generator/) looks like it might be a good solution.
It looks like it has built in support for thumbnail caching too, so 2 birds with 1 stone.

**Comment by cirillom** [comment]
preview-generator seemed like a good option, but after searching for a bit and trying to make it work it seems like it's more of a debian library. 

I found this guy [thumbnail](https://pypi.org/project/thumbnail/). Seems to have support for way more files than preview-generator and is not debian focused. Our only problem is that both of them needs a LOT of dependencies that are not easily installed.

**Comment by Icosahunter** [comment]
Yeah, I hadn't looked at it in depth. I did notice the few things I found seemed to have tons of dependencies. I guess that's to be expected, dealing with all sorts of file types is no easy task so you end up just grabbing libraries for each one.

Maybe one option would be to grab thumbnails from the system file manager's cache? It would be system dependent, but potentially the implementation would be simple enough to make it workable for all the major ones.

**Comment by vitnetdev** [comment]
What is currently used for video thumbnails in this project?

**Comment by CyanVoxel** [comment]
> What is currently used for video thumbnails in this project?

FFmpeg

**Comment by CyanVoxel** [comment]
PDF previews implemented in #543 (port of #378)
SVG previews implemented in #540 (port of #442)
