### ISSUE TITLE
[Bug]: "Fix Unlinked Entries" not functioning, only returns `None` count

### ISSUE THREAD

**Issue by CyanVoxel** [TagStudioDev/TagStudio#652]
### Checklist

- [X] I am using an up-to-date version.
- [X] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [X] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

`main` branch (v9.5.0)

### Operating System & Version

macOS 15.1.1

### Description

Using the "Fix Unlined Entries" tool only ever returns "None" as the count value, even if there are unlinked entries present in the library.

This seems to stem from [this](https://github.com/TagStudioDev/TagStudio/blob/934c98a4d486e36257054022c44b3901eae12596/tagstudio/src/qt/modals/fix_unlinked.py#L129) change made to `fix_unlinked.py` in #528. From what I can tell it seems that `set_missing_count()` is being passed as a callable function to `from_iterable_function` and is being called when the `done` signal inside its CustomRunnable `r` is emitted - however *without* any count argument passing to `set_missing_count()`, resulting in the method's default behavior of setting the count to `None`.

### Expected Behavior

Refreshing the unlinked entries method should return the count of the unlinked entries, and a 0 if none are found. Note that the "None" text currently being shown is not a result of there being no unlinked entries, but rather is an errant `None` value being displayed as the count.

### Steps to Reproduce

1. Open a TagStudio library
2. Move or delete a present in the library on disk to create an "unlinked entry"
3. Go to "Tools -> Fix Unlinked Entries" and click "Refresh All"
4. Note how the count now always says "Unlinked Entries: None"

5. Bonus: Repeat the previous steps while omitting step 2, noting the same result

**Comment by SkeleyM** [comment]
id like to work on this
