### ISSUE TITLE
Fix Open In File Manager for Linux

### ISSUE THREAD

**Issue by Icosahunter** [TagStudioDev/TagStudio#81]
The current implementation assumes the file manager is Nautilus. As a Linux fallback we can use "xdg-open" passing in the parent folder for the file in question, this won't select the file but it will open the folder the file is located in, in a file manager agnostic way. It looks like KDE Dolphin supports the "--select" option so we can add support for that too.
Also I recommend changing the tooltip from "open in explorer" to "open in file manager" or "open in file browser" so the language is platform agnostic.

**Comment by xarvex** [comment]
It looks like this also causes a freeze, I assume because a blocking API being used. I will have a fix ready shortly.
