### ISSUE TITLE
[Suggestion] File name displayed in grid view

### ISSUE THREAD

**Issue by Thesacraft** [TagStudioDev/TagStudio#85]
Maybe displaying the filename next to the file type would be helpfull. Because currently their is no real difference between diffrent files when no preview is available. So this would make it a lot easier to distinguish files without previews.

**Comment by MarlonVisser** [comment]
This would make it functional for relational databases, template databases, logbooks and lots more. This would multiply the use of your application by a lot of times. It'd open up a whole new set of promotion & advertising, just saying haha.

Yours sincerely

**Comment by MarlonVisser** [comment]
Would it be possible to assign a priority to this ticket in the development?

**Comment by CyanVoxel** [comment]
Got a quick version of this going, I'll open up a draft PR for it in the meantime

![image](https://github.com/user-attachments/assets/61bd187b-abba-4d08-b91c-1fb86975936f)
