### ISSUE TITLE
(Question) Directories

### ISSUE THREAD

**Issue by Ekirou** [TagStudioDev/TagStudio#90]
Where is the file which the directories I add in TagStudio are saved in?

**Comment by Loran425** [comment]
This is spot on, if you have a library `library_root` tagstudio drops a folder `library_root\.TagStudio` that contains all the backups and collages generated as well as the database at `library_root\.TagStudio\ts_library.json`. 

The only other external file generated is a `TagStudio.ini` file that saves the last loaded directory. This file is stored in the directory where Tagstudio runs. 

Feel free to reopen if you've got any additional questions.
